---

- name: download get_pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/local/bin/get_pip.py
    mode: 0755
  environment:
    http_proxy: "{{ http_proxy }}"

- name: install pip
  command: python2.7 /usr/local/bin/get_pip.py
  args:
    creates: /usr/local/bin/pip2

- name: install virtualenv
  pip:
    name: virtualenv
    state: present
